cache:
  directories:
    - "$HOME/.m2"
language: java
jdk:
  - openjdk8
before_install: 
  - cd src
install: mvn --no-transfer-progress -B -U install -DskipTests=true
before_script:
  - psql -c 'create database geogig_tests;' -U postgres
  - psql -c "create extension postgis" -U postgres -d geogig_tests
  - psql -f geotools/src/test/resources/features/online/geogig_pg_test.sql -U postgres -d geogig_tests
  - echo '[postgres]' > ~/.geogig-pg-backend-tests.properties
  - echo 'enabled = true' >> ~/.geogig-pg-backend-tests.properties
  - echo 'server = localhost' >> ~/.geogig-pg-backend-tests.properties
  - echo 'database = geogig_tests' >> ~/.geogig-pg-backend-tests.properties
  - echo 'user = postgres' >> ~/.geogig-pg-backend-tests.properties
  - echo 'password = ' >> ~/.geogig-pg-backend-tests.properties
  - echo '[database]' > ~/.geogig-pg-tests.properties
  - echo 'server = localhost' >> ~/.geogig-pg-tests.properties
  - echo 'database = geogig_tests' >> ~/.geogig-pg-tests.properties
  - echo 'user = postgres' >> ~/.geogig-pg-tests.properties
  - echo 'password = ' >> ~/.geogig-pg-tests.properties
script:
  - mvn --no-transfer-progress -B test
services: postgresql
addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.3
notifications:
  email: false
